rules:

  ######### Possible Errors
  no-extra-parens:
    - warn
    - all

  #### Best Practices
  curly:           # google = off
    - warn
    - multi-line
  dot-location:     # google = off
    - warn
    - property
  dot-notation: warn     # google = off

  ######### ECMAScript 6
  arrow-body-style: warn      # default = off
  arrow-spacing: warn     # default = off
  no-useless-constructor: warn      # default = off
  object-shorthand: warn      # default = off
  prefer-destructuring:      # default = off
    - warn
    - object: true
      array: true
  prefer-template: warn      # default = off
  #sort-imports:
  template-curly-spacing: error      # default = off

  #### Stylistic Issues
  array-bracket-spacing:
    - warn
    - always
    - singleValue: true
      objectsInArrays: false
      arraysInArrays: false
  block-spacing:
    - warn
    - always
  brace-style:
    - warn
    - stroustrup
  #camelcase:       # google: [2, {properties: 'never'}],
  #  - warn
  #  - properties: never
  capitalized-comments: off
  #comma-dangle:      # google: [2, 'always-multiline'],
  #  - warn
  #  - always-multiline
  #comma-spacing: warn      # google: error
  #comma-style: warn        # google: error
  #computed-property-spacing: warn      # google: error
  #consistent-this: off     # google: isn't used
  #eol-last: warn      # google: error
  #func-call-spacing: warn      # google: error
  #func-name-matching: off     # google: isn't used
  #func-names: off     # google: isn't used
  #func-style:     # google: isn't used
  #  - warn
  #  - expression
  # bad function names
  id-blacklist:
    - warn
    - 'set'
    - 'get'
    - 'delete'
  id-length:
    - warn
    - min: 2
      max: 35
      exceptions: ["i", "_", "p"]
  # Use CamelCase for variables and functions names
  id-match:
    - warn
    - "^[_$]*([A-Za-z]+)*$"
    - properties: false
  indent:
    - warn
    - 2
    - SwitchCase: 1
  jsx-quotes:
    - warn
    - prefer-double
  #key-spacing: warn      # google: error
  keyword-spacing: warn      # google: off
  #line-comment-position: off     # google: isn't used
  #linebreak-style: warn      # google: error
  lines-around-comment:     # google: isn't used
    - warn
    - beforeBlockComment: true
      allowBlockStart: true
      allowObjectStart: true
      allowArrayStart: true
  #lines-around-directive: off     # google: isn't used
  max-depth: warn     # google: isn't used
  max-len:      # see google defaults
    - warn
    - 160
    - tabWidth: 2
    - ignoreUrls: true
  #max-lines: off     # google: isn't used
  #max-nested-callbacks: warn     # google: isn't used
  #max-params: off     # google: isn't used
  max-statements:
    - warn
    - max: 10
    - ignoreTopLevelFunctions: true
  max-statements-per-line: warn     # google: isn't used
  multiline-ternary: off      # google: isn't used
  #new-cap: warn      # google: error
  new-parens: warn     # google: isn't used
  #newline-after-var: off     # google: isn't used
  newline-before-return: warn     # google: isn't used
  #newline-per-chained-call: off     # google: isn't used
  #no-array-constructor: warn      # google: error
  no-bitwise: warn     # google: isn't used
  no-continue: warn     # google: isn't used
  #no-inline-comments: off     # google: isn't used
  no-lonely-if: warn     # google: isn't used
  no-mixed-operators: warn     # google: isn't used
  no-multi-assign: warn
  #no-multiple-empty-lines:      # google: [2, {max: 2}],
  no-negated-condition: warn     # google: isn't used
  no-nested-ternary: warn     # google: isn't used
  #no-new-object: warn      # google: error
  no-plusplus:     # google: isn't used
    - warn
    - allowForLoopAfterthoughts: true
  #no-restricted-syntax: off     # google: isn't used
  no-tabs: warn     # google: isn't used
  #no-ternary: off     # google: isn't used
  #no-trailing-spaces: warn      # google: error
  no-underscore-dangle:     # google: isn't used
    - warn
    - allowAfterThis: true
  no-unneeded-ternary: warn     # google: isn't used
  no-whitespace-before-property: warn     # google: isn't used
  #nonblock-statement-body-position: off
  object-curly-newline: warn     # google: isn't used
  object-curly-spacing:      # google: error
    - warn
    - always
    - arraysInObjects: true
      objectsInObjects: true
  #object-property-newline: off     # google: isn't used
  #one-var:     # see google conf
  one-var-declaration-per-line:     # google: isn't used
    - warn
    - always
  operator-assignment: warn     # google: isn't used
  operator-linebreak:
    - warn
    - before
  #padded-blocks: off     # google: [2, 'never'],
  quote-props:      # google: [2, 'consistent'],
    - warn
    - as-needed
  #quotes:      # google: [2, 'single', {allowTemplateLiterals: true}],
  semi:     # google: error
    - warn
    - always
    - omitLastInOneLineBlock: true
  #semi-spacing: warn     # google: error
  #sort-keys: off     # google: isn't used
  #sort-vars: off     # google: isn't used
  #space-before-blocks: warn     # google: error
  #space-before-function-paren: # google: [2, 'never'],
  #space-in-parens:     # google: isn't used
  #  - warn
  #  - never
  #  - exceptions: ["{}", "[]"]
  space-infix-ops: warn     # google: isn't used
  space-unary-ops:     # google: isn't used
    - warn
    - words: true
      nonwords: false
      overrides:
        '-': true
        '+': true
  #spaced-comment: # google [2, 'always'],
  template-tag-spacing: warn
  #unicode-bom: off     # google: isn't used
  wrap-regex: warn     # google: isn't used
