# to Disallow Node.js modules, see http://eslint.org/docs/rules/no-restricted-modules
# Bkacklist for functuon names - http://eslint.org/docs/rules/id-blacklist

env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'google'
  - './.eslintrc-lib-lint.yml'
  - './.eslintrc-lib-style.yml'
  - './.eslintrc-lib-jsdoc.yml'
parser: babel-eslint

parserOptions:
  sourceType: module
#  codeFrame: false

#globals:
#  var1: true

rules:
  require-jsdoc: off
  valid-jsdoc: off

  # Recommends to reassign for your project specific
  #require-jsdoc: off
  no-console: warn
  no-warning-comments: off        # Useful in production - comments like TO DO etc
  #no-restricted-properties: error      # it's for deprecated props
  #no-restricted-modules: error       # list of restricted modules such ad os, fs etc.
  #no-restricted-imports              # list of restricted modules such ad os, fs etc.


  ######### Only for web
  no-alert: error   # google = off

  ######### Only for nodejs
  no-process-exit: error     # default = off
  no-path-concat: error     # default = off
  no-process-env: warn     # default = off
  #no-sync: off     # default = off
