# to Disallow Node.js modules, see http://eslint.org/docs/rules/no-restricted-modules
# Bkacklist for functuon names - http://eslint.org/docs/rules/id-blacklist

env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'google'
  - './.eslintrc-lib-lint.yml'
  - './.eslintrc-lib-style.yml'
  - './.eslintrc-lib-jsdoc.yml'
parser: babel-eslint

parserOptions:
  sourceType: module
#  codeFrame: false

#globals:
#  var1: true
