rules:

  # Recommends to reassign for your project specific
  require-jsdoc: off
  no-console: warn
  no-warning-comments: off        # Useful in production - comments like TO DO etc
  #no-restricted-properties: error      # it's for deprecated props
  #no-restricted-modules: error       # list of restricted modules such ad os, fs etc.
  #no-restricted-imports              # list of restricted modules such ad os, fs etc.

  ######### Possible Errors
  no-await-in-loop: warn
  no-compare-neg-zero: error
  no-cond-assign: warn    # google = off
  #no-irregular-whitespace: error   # google = error
  #no-prototype-builtins: off     # google = off
  #no-template-curly-in-string: off     # google = off
  #no-unexpected-multiline: error      # google = error
  no-unsafe-negation: warn      # google = off

  ######### Best Practices
  accessor-pairs: warn      # google = off
  array-callback-return: warn    # google = off
  #block-scoped-var: off     # google = off - unnecessary if no-var: error
  #class-methods-use-this: off      # google = off
  complexity:     # google = off
    - warn
    - 5
  #consistent-return: off     # google = off
  #default-case: off     # google = off
  eqeqeq:     # google = off
    - warn
    - smart
  #guard-for-in: error   # google = error
  #no-caller: error   # google = error
  no-div-regex: warn     # google = off
  #no-else-return: off     # google = off
  #no-empty-function: off     # google = off
  no-eq-null: error     # google = off
  no-eval: error     # google = off
  #no-extend-native: error     # google = error
  #no-extra-bind: error      # google = error
  no-extra-label: error     # google = off
  no-floating-decimal: error     # google = off
  no-global-assign: error     # google = off
  #no-implicit-coercion: off     # google = off
  #no-implicit-globals: off     # google = off
  no-implied-eval: error     # google = off
  #no-invalid-this: error     # google = error
  no-iterator: error     # google = off
  no-labels: error     # google = off
  no-lone-blocks: error     # google = off
  no-loop-func: error     # google = off
  no-magic-numbers: warn     # google = off
  no-multi-spaces:     # google = error
    - warn
    - exceptions:
        Property: true
        VariableDeclarator: true
        ImportDeclaration: true
  #no-multi-str: error     # google = error
  no-new: warn     # google = off
  no-new-func: error     # google = off
  #no-new-wrappers: error     # google = error
  no-octal-escape: error     # google = off
  no-param-reassign:     # google = off
    - error
    - props: false
  no-proto: error     # google = off
  no-return-assign: error     # google = off
  no-return-await: warn
  no-script-url: error     # default = off
  no-self-compare: error     # default = off
  no-sequences: error     # default = off
  #no-throw-literal: error     # google = error
  #no-unmodified-loop-condition: off      # default = off
  no-unused-expressions: warn     # default = error
  no-useless-call: error     # default = off
  no-useless-concat: error     # default = off
  no-useless-escape: warn     # default = off
  no-useless-return: warn
  no-void: error     # default = off
  #no-with: error     # google = error
  prefer-promise-reject-errors: warn
  #radix: off     # default = off
  require-await: warn
  #vars-on-top: off      # unnecessary if no-var: error
  wrap-iife:      # default = off
    - error
    - inside
  yoda: error     # default = off

  ######### Strict mode
  strict: off

  ######### Variables
  #init-declarations: off     # default = off
  #no-catch-shadow: off     # default = off
  #no-label-var: off     # default = off
  no-restricted-globals: error     # default = off
  no-shadow:     # default = off
    - error
    - hoist: all
  no-shadow-restricted-names: error     # default = off
  no-undef-init: warn
  no-undefined: warn     # default = off
  no-unused-vars:     # google = [2, {args: 'none'}]
    - error
    - vars: all
      args: after-used
  #no-use-before-define: error      # unnecessary if no-var: error

  ######### Node.js and CommonJS
  callback-return: error     # default = off
  global-require: warn     # default = off
  handle-callback-err: warn     # default = off
  no-mixed-requires: error     # default = off
  no-new-require: error     # default = off

  ######### ECMAScript 6
  arrow-body-style: warn      # default = off
  #arrow-parens:      # google [2, 'always']
  #constructor-super: error     # google = error
  #generator-star-spacing: # google = [2, 'after']
  no-class-assign: error      # default = off
  no-confusing-arrow: warn      # default = off
  no-duplicate-imports: warn      # default = off
  #no-new-symbol: error     # google = error
  #no-this-before-super: error      # google = error
  no-useless-computed-key: warn      # default = off
  no-useless-rename: warn      # default = off
  #no-var: error      # google = error
  prefer-arrow-callback: warn      # default = off
  prefer-const: error      # default = off
  prefer-numeric-literals: warn      # default = off
  #prefer-rest-params: error      # google = error
  #prefer-spread: error      # google = error
  #rest-spread-spacing: error      # google = error
  symbol-description: warn      # default = off
  #yield-star-spacing:      # google = [2, 'after']

  # !!! Not shure
  max-len:
    - warn
    - 160
    - 4
#  lines-around-comment:
#    - warn
#    - beforeBlockComment: true
#      afterBlockComment: true
#      allowBlockEnd: true
#      allowObjectStart: true
#      allowObjectEnd: true
#      allowArrayStart: true
#      allowArrayEnd: true


######### Only for web
  no-alert: error   # google = off

######### Only for nodejs
  no-process-exit: error     # default = off
  no-path-concat: error     # default = off
  no-process-env: warn     # default = off
  #no-sync: off     # default = off
