rules:
  require-jsdoc:
    - warn
    - require:
        FunctionDeclaration: false
        MethodDefinition: true
  valid-jsdoc:
    - warn
    - requireReturnType: true
      requireReturn: false
      matchDescription: "^[A-Z][A-Za-z0-9\\s\\`\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\_\\-\\+\\=\\|\\\"\\'\\;\\:\\?\\/\\>\\<\\.\\,\\[\\]\\{\\}\\\\]+$"
      prefer:
        return: returns
      preferType:
        String: string
        Object: object
        Array: array
        Boolean: boolean
        Number: number
