rules:

  ######### Possible Errors
  no-extra-parens:
    - warn
    - all

  #### Best Practices
  curly:           # google = off
    - warn
    - multi-line
  dot-location:     # google = off
    - warn
    - property
  dot-notation: warn     # google = off

  ######### ECMAScript 6
  arrow-spacing: warn     # default = off
  no-useless-constructor: warn      # default = off
  object-shorthand: warn      # default = off
  prefer-destructuring:      # default = off
    - warn
    - object: true
      array: true
  prefer-template: warn      # default = off
  # TODO: !!!! sort-imports
  #sort-imports
  template-curly-spacing: error      # default = off

  #### Stylistic Issues
  array-bracket-spacing:
    - warn
    - always
    - singleValue: true
      objectsInArrays: false
      arraysInArrays: false
  block-spacing:
    - warn
    - always
  brace-style:
    - warn
    - stroustrup
  camelcase:
    - warn
    - properties: never
  comma-dangle:
    - warn
    - always-multiline
  comma-spacing:
    - warn
    - before: false
      after: true
  comma-style:
    - warn
    - last
  computed-property-spacing:
    - warn
    - never
  consistent-this:
    - warn
    - that
  eol-last: warn
  func-names: off
  func-style:
    - warn
    - expression
  id-length:
    - warn
    - min: 2
      max: 25
      exceptions: ["i", "_"]
  # Use CamelCase for variables and functions names
  id-match:
    - warn
    - "^_?([A-Za-z]+)*$"
    - properties: false
  indent:
    - warn
    - 2
    - SwitchCase: 1
  jsx-quotes:
    - warn
    - prefer-double
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
  keyword-spacing: warn
  linebreak-style:
    - warn
    - unix
  max-depth:
    - warn
    - 4
  max-nested-callbacks:
    - warn
    - 3
  max-params:
    - warn
    - 5
  max-statements:
    - warn
    - 10
    - ignoreTopLevelFunctions: true
  max-statements-per-line:
    - warn
    - max: 1
  new-cap: warn
  new-parens: warn
  newline-after-var:
    - warn
    - always
  newline-before-return: warn
  newline-per-chained-call: warn
  no-array-constructor: warn
  no-bitwise: warn
  no-continue: warn
  no-inline-comments: off
  no-lonely-if: warn
